travis:
  secure:
    BINSTAR_TOKEN: Pw/J9/W59GV78PXcPuqyl3KvMvf0Dfb3PkVeTHxn7mXLOtN27z9q79OorLQspTdFBre4VR985etGnH20+iYD8T3dHuxBdNdYYYp6qUOSZuQd7LUR5CD4azes6rD9CQ3FuK7k3nnd45AcgnvWtbYEuuSbSI5DbiXI82+0b3hBB5E85kTkAgWRLNX709vgU9+AT9qDEHRYrhyJcvNYcmEKz/oUV3DjeGkNUYav4PaSFFymah8YApY7L0R05GNI8Fx8UHL//iVsXAoxJYR/f0QfvNHLZJY+g24Km34shDQtElB7Bp8ZE4juIz/j5iWRy+nmMT5UgRvDO5CnP5vzB8LeFhSXvu3JVcVw8IrnKk4QIQI1XaO7m9c1td0rADsTPRoPe2U4Vm4CXd7+jAW6ZI5ZcARjCNATYZof1s/mW/S/Z1ByuGb/3QSsaIeO0KuWajw0Cu1WtbMbMUf2aEVN2W44G2TwcNp1+nwGGsKzleSdBg71HCs9Re1AHA1NLmK4H/L9+R/iwhCnFoigq11VzX6+gjByx3vua2F3RA2sLHrgp3ie1OGMBGgi+UrY1GiGj87DsRFXiCzzVC27NHie6uqiPSxNHpoIMK9s5pLWTDDP++Jym/JPm9PtilKvu/KLzEbUWzSYLtwHt99ljaJlOgsvDzNE1tVu24q2iBZxG34IIX0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
