travis:
  secure:
    BINSTAR_TOKEN: wlvvhk3+zu8nd+Z7wv3HC4nLNkeo1sB9KXWktSQ3s5NgVkpvFWWOkgXd3XQtnm/wcS+RyE51tptArvFK/QNlSlEfTkKBQuZUncdJZLIWRs8t8tXVJ460PYJ1TD3a58PFeTb0xcrM4/Qb1LjUgiJwlD89CeyA6TcTBIV2XFQY1AkG0RxzY4tFKmiuV1AdKp6DZvY+hSZ+aTwSUHESGmBKfZfHT0vKeoRmmlvcOAdVX7r0EzxVHYhjVovVtLBLhtJxGWvCBNwhAuRLJ91rvx4MCzD6xORXqFxopLw3SVD2sWdEyLa417NSwDvRWBRtmBxycDaUC+wwHzXXEZgafQBIaZ4U1uqXwISQIGZd+subWZRLSaR9qN3zLd659EmS/yjtH9i3jZ8XqjP9SYWrJY5aJAXIoO3ejk4iITQH40YgmONtJad2+9qcQwlSqyU/qu955yxIhO9FfcVHTgw5rqpHZg94GMJMhe32Dkxe7YF/FYDbFFIPCrBn8taCFSHd5YH/naHAchrdDPFSLbDO1HiMy4JnT3Fbaf1Sq7o2TE/fIwrLp5jd4kAmXJTKQrrb2pdEjtXkYJqDlpJ/g9K3CtBSnM5HzZ9pj7l2O5DtV0JN7hKOCwNLMTH3EjH1nlHXjWPDZ98zi6HupYYmSpkKyApyimzTHXPANo5f1gmxnUHEGSM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
